// lib/parse-dream.js — dream string → slug + vision.md + slice.md
// SRP (constitution §I.S): owns dream parsing and initial state-doc generation.
// Public API: slugify, initStateFiles, nextAvailableSlug, STOPWORDS.

import { writeFile, access } from 'node:fs/promises';
import path from 'node:path';

import { ensureLayout } from './state.js';

/**
 * Stop-words removed during slugification. Exported for tests + future reuse.
 */
export const STOPWORDS = Object.freeze([
  'a', 'an', 'the', 'that', 'on', 'of', 'for', 'to', 'in', 'with', 'and', 'or',
]);

const SLUG_MAX_LEN = 64;

/**
 * Deterministic slugifier.
 *  1. NFKD-normalize and strip diacritics (escape form mandated per F9).
 *  2. Lowercase, replace non `[a-z0-9]+` with `-`.
 *  3. Drop stop-words.
 *  4. Trim leading/trailing `-`.
 *  5. Truncate to 64 chars (cut at last `-` boundary if possible).
 *  6. Empty result -> TypeError.
 *
 * @param {string} input
 * @returns {string}
 */
export function slugify(input) {
  if (typeof input !== 'string') {
    throw new TypeError('slugify: dream must be a string');
  }
  // 1. Normalize + strip combining marks. Use escape form, never raw bytes.
  const normalized = input.normalize('NFKD').replace(/[̀-ͯ]/g, '');
  // 2. Lowercase + non-ascii-alnum → `-`.
  const replaced = normalized.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  // 3. Split, drop stop-words and empty fragments.
  const parts = replaced.split('-').filter((p) => p.length > 0 && !STOPWORDS.includes(p));
  // 4. Re-join.
  let slug = parts.join('-');
  // 5. Truncate at last `-` boundary <= 64.
  if (slug.length > SLUG_MAX_LEN) {
    let cut = slug.slice(0, SLUG_MAX_LEN);
    const lastDash = cut.lastIndexOf('-');
    if (lastDash > 0) cut = cut.slice(0, lastDash);
    slug = cut;
  }
  // 4 (repeat): the truncate may have left a trailing dash.
  slug = slug.replace(/^-+|-+$/g, '');
  // 6. Empty -> TypeError.
  if (slug.length === 0) {
    throw new TypeError(
      'slugify: dream string yields empty slug — v0.1 supports ASCII-derivable dreams only'
    );
  }
  return slug;
}

/**
 * Write vision.md and slice.md under <demoDir>/.mmd/shared/.
 * Does NOT create status.json (lazy — see F1-round-3).
 *
 * Pre-condition: ensureLayout(demoDir) has been called by the orchestrator.
 */
export async function initStateFiles(demoDir, dream, slug) {
  // Defense: ensureLayout is idempotent — running it again is cheap and prevents
  // ENOENT if the caller forgot.
  await ensureLayout(demoDir);

  const visionTemplate =
    `# Vision\n\n` +
    `Long-term vision for: ${dream}\n\n` +
    `(Auto-generated by mmd v0.1 — to be expanded in v0.3a Dream Expander)\n`;

  const sliceTemplate =
    `# Slice — ${slug}\n\n` +
    `Dream: ${dream}\n\n` +
    `v0.1 walking-skeleton scope:\n` +
    `- PWA in ./demo/${slug}/\n` +
    `- Vanilla HTML/CSS/JS + Canvas API + getUserMedia\n` +
    `- Bundle B safe-default: camera permission on user gesture only\n\n` +
    `Acceptance summary: see SPEC_V01.md AC-4.\n`;

  const sharedDir = path.join(demoDir, '.mmd', 'shared');
  await writeFile(path.join(sharedDir, 'vision.md'), visionTemplate, 'utf8');
  await writeFile(path.join(sharedDir, 'slice.md'), sliceTemplate, 'utf8');
}

/**
 * Probe `<demoRoot>/<base>-2`, `-3`, ... and return the first basename whose
 * directory does NOT exist. Cap at -999 to avoid runaway loops.
 */
export async function nextAvailableSlug(base, demoRoot) {
  for (let n = 2; n < 1000; n++) {
    const candidate = `${base}-${n}`;
    try {
      await access(path.join(demoRoot, candidate));
      // exists — try next suffix
    } catch (err) {
      if (err && err.code === 'ENOENT') return candidate;
      // Anything else (EACCES on the parent, etc.) — surface loudly.
      throw err;
    }
  }
  throw new Error(`nextAvailableSlug: exhausted -2..-999 suffixes for ${base}`);
}
