// lib/parse-dream.js — dream string → slug + vision.md + slice.md
// SRP (constitution §I.S): owns dream parsing and initial state-doc generation.
// Public API: slugify, initStateFiles, nextAvailableSlug, STOPWORDS.

import { writeFile, access } from 'node:fs/promises';
import path from 'node:path';

import { ensureLayout } from './state.js';

/**
 * Stop-words removed during slugification. Exported for tests + future reuse.
 */
export const STOPWORDS = Object.freeze([
  'a', 'an', 'the', 'that', 'on', 'of', 'for', 'to', 'in', 'with', 'and', 'or',
]);

const SLUG_MAX_LEN = 64;

/**
 * Deterministic slugifier.
 *  1. NFKD-normalize and strip diacritics (escape form mandated per F9).
 *  2. Lowercase, replace non `[a-z0-9]+` with `-`.
 *  3. Drop stop-words.
 *  4. Trim leading/trailing `-`.
 *  5. Truncate to 64 chars (cut at last `-` boundary if possible).
 *  6. Empty result -> TypeError.
 *
 * @param {string} input
 * @returns {string}
 */
export function slugify(input) {
  if (typeof input !== 'string') {
    throw new TypeError('slugify: dream must be a string');
  }
  // 1. Normalize + strip combining marks. Use escape form, never raw bytes.
  const normalized = input.normalize('NFKD').replace(/[̀-ͯ]/g, '');
  // 2. Lowercase + non-ascii-alnum → `-`.
  const replaced = normalized.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  // 3. Split, drop stop-words and empty fragments.
  const parts = replaced.split('-').filter((p) => p.length > 0 && !STOPWORDS.includes(p));
  // 4. Re-join.
  let slug = parts.join('-');
  // 5. Truncate at last `-` boundary <= 64.
  if (slug.length > SLUG_MAX_LEN) {
    let cut = slug.slice(0, SLUG_MAX_LEN);
    const lastDash = cut.lastIndexOf('-');
    if (lastDash > 0) cut = cut.slice(0, lastDash);
    slug = cut;
  }
  // 4 (repeat): the truncate may have left a trailing dash.
  slug = slug.replace(/^-+|-+$/g, '');
  // 6. Empty -> TypeError.
  if (slug.length === 0) {
    throw new TypeError(
      'slugify: dream string yields empty slug — v0.1 supports ASCII-derivable dreams only'
    );
  }
  return slug;
}

// Fixed scaffolding of an MMD launch dream — "implement vX per SPEC_Y.md, spec
// is frozen, skip party mode, …". These phrases say nothing about WHAT a slice
// does, yet they sit at the FRONT of the dream, so a naive slug captures them
// instead of the work. Stripped ONLY for branch-name derivation (below), never
// from the general `slugify` (which feeds slice_id / state — wider blast
// radius). Order matters: the specific `SPEC_X.md` token is removed before the
// generic `per spec`, so neither leaves a dangling fragment.
// See constitution universal.md §VII (Human-readable first).
const BRANCH_BOILERPLATE = Object.freeze([
  /\bSPEC_[A-Z0-9_]+\.md\b/gi,
  /\bper\s+spec\b/gi,
  /\bspec\s+is\s+(authoritative\s+and\s+)?frozen\b/gi,
  /\bdo\s+not\s+(edit|modify)(\s+it)?\b/gi,
  /\bskip\s+party\s+mode\b/gi,
  /\bgo\s+directly\s+to\s+implementation\b/gi,
  /\bimplement(ation)?\b/gi,
  /\bauthoritative\b/gi,
  /\bfrozen\b/gi,
  /\bdeliver\b/gi,
  // Standalone `per` left orphaned once `SPEC_X.md` / `per spec` are stripped.
  /\bper\b/gi,
]);

/**
 * Derive a human-readable branch slug for `mmdream --here` (universal.md §VII).
 *
 * Precedence:
 *   1. An explicit `--label` (already a short human phrase) → slugified directly.
 *   2. Otherwise the dream with launch boilerplate stripped, so the slug reads
 *      like the work ("wip-salvage-stall-signal") rather than the preamble
 *      ("implement-v0-2-n-per-spec-v02n-md-spec-is-frozen-do-not-edit-it-…").
 *
 * Always returns a NON-EMPTY slug: if boilerplate-stripping empties the text,
 * it falls back to slugifying the raw dream (the legacy behavior), which only
 * throws when the dream itself is non-ASCII-derivable.
 *
 * @param {string} dream
 * @param {string} [explicitLabel]
 * @returns {string}
 */
export function deriveBranchSlug(dream, explicitLabel) {
  if (typeof explicitLabel === 'string' && explicitLabel.trim().length > 0) {
    return slugify(explicitLabel);
  }
  if (typeof dream !== 'string') {
    throw new TypeError('deriveBranchSlug: dream must be a string');
  }
  let stripped = dream;
  for (const re of BRANCH_BOILERPLATE) stripped = stripped.replace(re, ' ');
  if (stripped.trim().length > 0) {
    try {
      return slugify(stripped);
    } catch {
      // Stripped text slugified to empty (all stop-words) — fall through to raw.
    }
  }
  return slugify(dream);
}

/**
 * Write vision.md and slice.md under <demoDir>/.mmd/shared/.
 * Does NOT create status.json (lazy — see F1-round-3).
 *
 * Pre-condition: ensureLayout(demoDir) has been called by the orchestrator.
 */
export async function initStateFiles(demoDir, dream, slug) {
  // Defense: ensureLayout is idempotent — running it again is cheap and prevents
  // ENOENT if the caller forgot.
  await ensureLayout(demoDir);

  const visionTemplate =
    `# Vision\n\n` +
    `Long-term vision for: ${dream}\n\n` +
    `(Auto-generated by mmdream v0.1 — to be expanded in v0.3a Dream Expander)\n`;

  const sliceTemplate =
    `# Slice — ${slug}\n\n` +
    `Dream: ${dream}\n\n` +
    `v0.1 walking-skeleton scope:\n` +
    `- PWA in ./demo/${slug}/\n` +
    `- Vanilla HTML/CSS/JS + Canvas API + getUserMedia\n` +
    `- Bundle B safe-default: camera permission on user gesture only\n\n` +
    `Acceptance summary: see SPEC_V01.md AC-4.\n`;

  const sharedDir = path.join(demoDir, '.mmd', 'shared');
  await writeFile(path.join(sharedDir, 'vision.md'), visionTemplate, 'utf8');
  await writeFile(path.join(sharedDir, 'slice.md'), sliceTemplate, 'utf8');
}

/**
 * Probe `<demoRoot>/<base>-2`, `-3`, ... and return the first basename whose
 * directory does NOT exist. Cap at -999 to avoid runaway loops.
 */
export async function nextAvailableSlug(base, demoRoot) {
  for (let n = 2; n < 1000; n++) {
    const candidate = `${base}-${n}`;
    try {
      await access(path.join(demoRoot, candidate));
      // exists — try next suffix
    } catch (err) {
      if (err && err.code === 'ENOENT') return candidate;
      // Anything else (EACCES on the parent, etc.) — surface loudly.
      throw err;
    }
  }
  throw new Error(`nextAvailableSlug: exhausted -2..-999 suffixes for ${base}`);
}
