// @unit tests for lib/discover/report.js — report shape with frozen clock.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';

import {
  buildReport,
  flipReportToValidated,
  writeReport,
} from '../../lib/discover/report.js';

const FROZEN_CLOCK = new Date('2026-05-17T12:00:00.000Z');

function baseScan() {
  return {
    methodologies: { spec_kit: true, bmad: true, stories_count: 3, mmd_md: false },
    languages: { top5: ['.js', '.json'], total: 5 },
    frameworks: { language: 'javascript', frameworks: ['react'], test_runner: 'vitest' },
    lint: { eslint: true, prettier: true, biome: false },
    git: { is_git_repo: true, default_branch: 'main', first_commit_iso: '2026-01-01T00:00:00.000Z', commits_last_90d: 17 },
  };
}

test('@unit buildReport: rich case → "Detected case" + all sections present + frozen timestamp', () => {
  const md = buildReport({
    targetDir: '/fake/target',
    scanData: baseScan(),
    ingestData: {
      spec_kit_constitution: { writtenPath: '/fake/.mmd/shared/constitution/imported.md' },
      bmad_stories: {
        writtenPath: '/fake/.mmd/shared/status.json',
        stories: [
          { id: 'a', status: 'done' },
          { id: 'b', status: 'in-progress' },
          { id: 'c', status: 'draft' },
        ],
      },
      openspec: null,
      loose_specs: null,
    },
    inferredMd: '# Inferred conventions\n\n## Stack\nJavaScript project',
    caseLabel: 'rich',
    version: '0.2.4',
    clock: FROZEN_CLOCK,
  });
  assert.match(md, /# MMD Discovery Report/);
  assert.match(md, /Generated by `mmd discover` at 2026-05-17T12:00:00\.000Z/);
  assert.match(md, /Status: PENDING VALIDATION/);
  assert.match(md, /MMD version: 0\.2\.4/);
  assert.match(md, /Rich \(Spec Kit \+ BMAD\)/);
  assert.match(md, /## Scanned/);
  assert.match(md, /## Ingested/);
  assert.match(md, /## Inferred/);
  assert.match(md, /## Hypotheses to validate/);
  assert.match(md, /## Suggested next step/);
});

test('@unit buildReport: blank case has the right label + hypotheses', () => {
  const md = buildReport({
    targetDir: '/fake',
    scanData: {
      methodologies: {},
      languages: { top5: [], total: 0 },
      frameworks: { language: 'javascript' },
      lint: {},
      git: { is_git_repo: true, default_branch: 'main', commits_last_90d: 0 },
    },
    ingestData: { spec_kit_constitution: null, bmad_stories: null, openspec: null, loose_specs: null },
    inferredMd: '# Inferred conventions\n\nstack',
    caseLabel: 'blank',
    version: '0.2.4',
    clock: FROZEN_CLOCK,
  });
  assert.match(md, /Blank \(no SDD methodology\)/);
  assert.match(md, /inferred stack section/);
});

test('@unit buildReport: bmad-alone case mentions the count + cross-check deferral', () => {
  const md = buildReport({
    targetDir: '/fake',
    scanData: {
      methodologies: { stories_count: 15 },
      languages: { top5: [], total: 0 },
      frameworks: {},
      lint: {},
      git: { is_git_repo: false },
    },
    ingestData: { bmad_stories: { stories: Array(15).fill({ status: 'done' }) } },
    inferredMd: '# Inferred conventions\n\nstack',
    caseLabel: 'bmad-alone',
    version: '0.2.4',
    clock: FROZEN_CLOCK,
  });
  assert.match(md, /BMAD-alone \(possible spec sprawl\)/);
  assert.match(md, /15 stories detected/);
  assert.match(md, /deferred to v0\.2c\+/);
});

test('@unit buildReport: contradiction surfaces when Spec Kit dir but no constitution', () => {
  const md = buildReport({
    targetDir: '/fake',
    scanData: {
      methodologies: { spec_kit: true },
      languages: { top5: [], total: 0 },
      frameworks: {},
      lint: {},
      git: { is_git_repo: false },
    },
    ingestData: { spec_kit_constitution: null },
    inferredMd: '# Inferred conventions\n\nstack',
    caseLabel: 'rich',
    version: '0.2.4',
    clock: FROZEN_CLOCK,
  });
  assert.match(md, /## Contradictions \/ surprises/);
  assert.match(md, /Spec Kit directory detected/);
});

test('@unit buildReport: same input → byte-identical output (determinism)', () => {
  const args = {
    targetDir: '/fake',
    scanData: baseScan(),
    ingestData: { spec_kit_constitution: null, bmad_stories: null, openspec: null, loose_specs: null },
    inferredMd: '# Inferred conventions\n\nstack',
    caseLabel: 'rich',
    version: '0.2.4',
    clock: FROZEN_CLOCK,
  };
  assert.equal(buildReport(args), buildReport(args));
});

test('@unit flipReportToValidated: replaces PENDING VALIDATION with VALIDATED at <iso>', () => {
  const input = '# r\n> Status: PENDING VALIDATION — review\n';
  const out = flipReportToValidated(input, FROZEN_CLOCK);
  assert.match(out, /Status: VALIDATED at 2026-05-17T12:00:00\.000Z/);
  assert.ok(!/PENDING VALIDATION/.test(out));
});

test('@unit flipReportToValidated: throws when no PENDING line', () => {
  assert.throws(
    () => flipReportToValidated('# r\nno status line\n'),
    /no `Status: PENDING VALIDATION` line found/,
  );
});

test('@unit writeReport: skipRootReport=true writes only last.md', async () => {
  const t = await mkdtemp(path.join(os.tmpdir(), 'mmd-rep-'));
  try {
    const w = await writeReport(t, '# r\n', { skipRootReport: true });
    assert.equal(w.rootPath, null);
    assert.ok(w.lastPath);
  } finally {
    await rm(t, { recursive: true, force: true });
  }
});

test('@unit writeReport: default mode writes both root + last', async () => {
  const t = await mkdtemp(path.join(os.tmpdir(), 'mmd-rep-'));
  try {
    const w = await writeReport(t, '# r\n');
    assert.ok(w.rootPath);
    assert.ok(w.lastPath);
  } finally {
    await rm(t, { recursive: true, force: true });
  }
});
