// @unit tests for lib/documentalist/coherence-report.js (SPEC_V07A AC-3 render).
//
// Pure render — no I/O. We feed crafted inventory + reconciliation objects and
// assert the markdown carries the mandated sections, the heuristic label, the
// doc-health flags, the inventory headline, and the honest --with-claude
// fallback note. < 100ms (testing.md §V).

import { test } from 'node:test';
import assert from 'node:assert/strict';

import { renderCoherenceReport } from '../../lib/documentalist/coherence-report.js';

const INVENTORY = {
  subcommands: ['serve', 'discover', 'document-review'],
  tags: ['v0.1.0', 'v0.6.1'],
  adrs: [
    { number: 1, title: 'Adopt gStack', file: '001.md' },
    { number: 33, title: 'Constitution suggestions', file: '033.md' },
  ],
  libModules: ['conductor', 'documentalist'],
  docLineCounts: [
    { doc: 'MAKE_MY_DREAMS.md', lines: 1722, overCap: true },
    { doc: 'README.md', lines: 150, overCap: false },
  ],
  docCap: 200,
  specCount: 33,
  lessonCount: 21,
};

const RECONCILIATION = {
  heuristic: true,
  note: 'heuristic — matched names; not an authoritative audit',
  entries: [
    { version: 'v0.3', capability: 'Dream Catcher', signal: 'lib dream-catcher', status: 'built' },
    { version: 'v0.4', capability: 'auto-handoff', signal: '(none)', status: 'partial' },
    { version: 'v0.3a', capability: 'Dream Expander', signal: '(none)', status: 'unbuilt' },
  ],
};

test('@unit report: renders the generated banner + heuristic disclaimer', () => {
  const md = renderCoherenceReport({ inventory: INVENTORY, reconciliation: RECONCILIATION });
  assert.match(md, /<!-- GENERATED by `mmd document-review`/);
  assert.match(md, /# MMD Coherence Review/);
  assert.match(md, /heuristic/i);
  assert.match(md, /not an authoritative audit/i);
});

test('@unit report: renders the designed-vs-built table with status glyphs', () => {
  const md = renderCoherenceReport({ inventory: INVENTORY, reconciliation: RECONCILIATION });
  assert.match(md, /## Designed vs built/);
  assert.match(md, /\| Dream Catcher \| v0\.3 \| lib dream-catcher \| ✅ built \|/);
  assert.match(md, /\| auto-handoff \| v0\.4 \| \(none\) \| 🟡 partial \|/);
  assert.match(md, /\| Dream Expander \| v0\.3a \| \(none\) \| ❌ unbuilt \|/);
  assert.match(md, /Legend:/);
});

test('@unit report: doc-health flags the cap violation + SPEC sprawl', () => {
  const md = renderCoherenceReport({ inventory: INVENTORY, reconciliation: RECONCILIATION });
  assert.match(md, /## Doc health/);
  assert.match(md, /MAKE_MY_DREAMS\.md: 1722 lines \(cap 200/);
  assert.match(md, /33 SPEC_V\*\.md at the repo root — sprawl/);
});

test('@unit report: clean repo → "No doc-health flags"', () => {
  const clean = {
    ...INVENTORY,
    docLineCounts: [{ doc: 'README.md', lines: 50, overCap: false }],
    specCount: 3,
  };
  const md = renderCoherenceReport({ inventory: clean, reconciliation: RECONCILIATION });
  assert.match(md, /No doc-health flags/);
});

test('@unit report: inventory headline + summary lines', () => {
  const md = renderCoherenceReport({ inventory: INVENTORY, reconciliation: RECONCILIATION });
  assert.match(md, /## Inventory  \(3 subcommands · 2 ADRs · 21 lessons · tags v0\.1\.0\.\.v0\.6\.1\)/);
  assert.match(md, /latest ADR-033 — Constitution suggestions/);
  assert.match(md, /\*\*Root SPEC files\*\*: 33/);
});

test('@unit report: --with-claude unavailable → honest fallback note, no fabrication', () => {
  const md = renderCoherenceReport({
    inventory: INVENTORY,
    reconciliation: RECONCILIATION,
    llm: { requested: true, enrichment: null, note: 'claude not on PATH' },
  });
  assert.match(md, /## LLM enrichment/);
  assert.match(md, /LLM enrichment unavailable: claude not on PATH/);
  assert.match(md, /No classification was fabricated/);
});

test('@unit report: --with-claude available → enrichment block rendered', () => {
  const md = renderCoherenceReport({
    inventory: INVENTORY,
    reconciliation: RECONCILIATION,
    llm: { requested: true, enrichment: 'The heuristic under-rates v0.5b: lite Documentalist only.', note: null },
  });
  assert.match(md, /under-rates v0\.5b/);
});

test('@unit report: no llm requested → no enrichment section', () => {
  const md = renderCoherenceReport({ inventory: INVENTORY, reconciliation: RECONCILIATION });
  assert.ok(!md.includes('LLM enrichment'));
});

// --- Drift / conformance section (SPEC_V07B AC-3) --------------------------

const DRIFT = {
  scannedDocs: 7,
  dangling: [
    { doc: 'README.md', line: 88, ref: 'ADR-099', kind: 'adr', reason: 'no docs/adr/099-*.md for ADR-099' },
    { doc: 'CLAUDE.md', line: 12, ref: 'lib/gone.js', kind: 'file', reason: 'file not found (renamed/removed?)' },
  ],
  staleFacts: [
    { doc: 'README.md', line: 31, claim: '30 ADRs', actual: 35 },
  ],
  semantic: { requested: false, text: null, note: null },
};

test('@unit report(drift): renders the Drift section with dangling refs + stale facts', () => {
  const md = renderCoherenceReport({ inventory: INVENTORY, reconciliation: RECONCILIATION, drift: DRIFT });
  assert.match(md, /## Drift \/ conformance/);
  assert.match(md, /flags\*\* drift, it does \*\*NOT\*\* edit your docs/);
  assert.match(md, /Scanned 7 truth docs/);
  assert.match(md, /### Dangling references/);
  assert.match(md, /⚠️ README\.md:88 → `ADR-099` — no docs\/adr\/099/);
  assert.match(md, /⚠️ CLAUDE\.md:12 → `lib\/gone\.js` — file not found/);
  assert.match(md, /### Stale facts/);
  assert.match(md, /⚠️ README\.md:31 says "30 ADRs" — inventory has 35/);
});

test('@unit report(drift): a clean repo renders the green "no drift" lines', () => {
  const md = renderCoherenceReport({
    inventory: INVENTORY,
    reconciliation: RECONCILIATION,
    drift: { scannedDocs: 5, dangling: [], staleFacts: [], semantic: { requested: false } },
  });
  assert.match(md, /✅ No dangling references/);
  assert.match(md, /✅ No stale facts/);
});

test('@unit report(drift): --with-claude semantic drift renders when present', () => {
  const md = renderCoherenceReport({
    inventory: INVENTORY,
    reconciliation: RECONCILIATION,
    drift: { ...DRIFT, semantic: { requested: true, text: 'ADR-029 describes a 70% auto-handoff that never shipped.', note: null } },
  });
  assert.match(md, /### Semantic drift/);
  assert.match(md, /never shipped/);
});

test('@unit report(drift): --with-claude unavailable → honest fallback, no fabricated verdict', () => {
  const md = renderCoherenceReport({
    inventory: INVENTORY,
    reconciliation: RECONCILIATION,
    drift: { ...DRIFT, semantic: { requested: true, text: null, note: 'claude not on PATH' } },
  });
  assert.match(md, /### Semantic drift/);
  assert.match(md, /LLM drift check unavailable: claude not on PATH/);
  assert.match(md, /no semantic-conformance verdict was fabricated/);
});

test('@unit report(drift): no drift payload → no Drift section (v0.7.a back-compat)', () => {
  const md = renderCoherenceReport({ inventory: INVENTORY, reconciliation: RECONCILIATION });
  assert.ok(!md.includes('## Drift / conformance'), 'back-compat: no drift arg → no section');
});

test('@unit report: empty/garbage args never throw, produce a minimal report', () => {
  assert.doesNotThrow(() => renderCoherenceReport());
  assert.doesNotThrow(() => renderCoherenceReport({}));
  const md = renderCoherenceReport({});
  assert.match(md, /# MMD Coherence Review/);
});
