// test/integration/document-review.test.js — CLI-level tests for `mmd
// document-review` (SPEC_V07A AC-3). We spawn the real bin/mmd.js child in a
// throwaway git repo so the dispatch wiring, the real fs/git gather, the
// reconcile + render, the single-file write, and the --with-claude seam are all
// covered end-to-end. Tagged @integration.
//
// The HEADLINE assertion is the READ-ONLY CONTRACT (SPEC §4): after a run, the
// ONLY changed tracked path is docs/coherence-review.md. L-016/L-019: every
// spawned child has a hard timeout.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtemp, writeFile, rm, mkdir, readFile, chmod } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = fileURLToPath(new URL('../../', import.meta.url));
const MMD = path.join(REPO_ROOT, 'bin', 'mmd.js');

const ROADMAP = [
  '# Make My Dreams',
  '',
  '## 9. MVP-first Roadmap',
  '',
  '### v0.3 — Dream Catcher conversational CLI  *(3–4 days)*',
  '### v0.3a — Dream Expander (real BMAD brainstorming)  *(4–5 days)*',
  '### v0.6 — Polymorphic Reality Check + Mockup  *(4-5 days)*',
  '',
].join('\n');

function git(cwd, args) {
  const r = spawnSync('git', args, { cwd, encoding: 'utf8', timeout: 20000 });
  if (r.status !== 0) throw new Error(`git ${args.join(' ')} failed: ${r.stderr}`);
  return r.stdout;
}

function runMmd(cwd, args, extraEnv = {}) {
  return spawnSync('node', [MMD, 'document-review', ...args], {
    cwd, encoding: 'utf8', timeout: 60000,
    env: { ...process.env, MMD_SKIP_SETUP: '1', MMD_SKIP_GROUNDING: '1', ...extraEnv },
  });
}

async function makeRepo() {
  const dir = await mkdtemp(path.join(tmpdir(), 'mmd-docreview-'));
  await mkdir(path.join(dir, 'docs', 'adr'), { recursive: true });
  await mkdir(path.join(dir, 'lib', 'documentalist'), { recursive: true });
  await writeFile(path.join(dir, 'MAKE_MY_DREAMS.md'), ROADMAP);
  await writeFile(path.join(dir, 'package.json'), JSON.stringify({ name: 'fixture', version: '0.7.0' }));
  await writeFile(path.join(dir, 'docs', 'adr', '001-x.md'), '# ADR-001 — Adopt gStack\n');
  await writeFile(path.join(dir, 'docs', 'lessons-learned.md'), '## L-001 — a\n**Status**: active\n');
  await writeFile(path.join(dir, 'SPEC_V01.md'), 'spec one\n');
  await writeFile(path.join(dir, 'README.md'), 'readme\n');
  git(dir, ['init', '-q']);
  git(dir, ['config', 'user.email', 't@t.t']);
  git(dir, ['config', 'user.name', 'T']);
  git(dir, ['add', '-A']);
  git(dir, ['commit', '-qm', 'baseline']);
  return dir;
}

test('@integration document-review: writes docs/coherence-review.md and prints a summary', async () => {
  const dir = await makeRepo();
  try {
    const r = runMmd(dir, []);
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /Coherence review written to docs\/coherence-review\.md/);
    assert.match(r.stdout, /Roadmap §9:/);
    assert.match(r.stdout, /Read-only: nothing else in the repo was modified/);

    const report = await readFile(path.join(dir, 'docs', 'coherence-review.md'), 'utf8');
    assert.match(report, /# MMD Coherence Review/);
    assert.match(report, /GENERATED by `mmdream document-review`/);
    // Big rocks classified honestly in the fixture roadmap.
    // In this bare fixture nothing named "expander"/"reality"/"mockup" exists,
    // so both classify unbuilt — the honest conservative default.
    assert.match(report, /Dream Expander.*❌ unbuilt/);
    assert.match(report, /Polymorphic Reality Check.*❌ unbuilt/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('@integration document-review: READ-ONLY — only docs/coherence-review.md changes', async () => {
  const dir = await makeRepo();
  try {
    const r = runMmd(dir, []);
    assert.equal(r.status, 0, r.stderr);
    // git status sees exactly one new/changed path: the report.
    const status = git(dir, ['status', '--porcelain']);
    const changed = status.split('\n').map((l) => l.slice(3)).filter(Boolean);
    assert.deepEqual(changed, ['docs/coherence-review.md'], `unexpected changes: ${status}`);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('@integration document-review: --dry-run prints, writes nothing', async () => {
  const dir = await makeRepo();
  try {
    const r = runMmd(dir, ['--dry-run']);
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /# MMD Coherence Review/);
    // Nothing written → clean tree.
    const status = git(dir, ['status', '--porcelain']);
    assert.equal(status.trim(), '', `dry-run must write nothing, got: ${status}`);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('@integration document-review: --with-claude success → enrichment block from the seam', async () => {
  const dir = await makeRepo();
  // A fake claude that prints commentary and exits 0.
  const fake = path.join(dir, 'fake-claude-ok.sh');
  await writeFile(fake, '#!/bin/sh\necho "- heuristic under-rates the lite Documentalist"\n');
  await chmod(fake, 0o755);
  try {
    const r = runMmd(dir, ['--with-claude'], { MMD_DOCUMENT_REVIEW_CMD: fake });
    assert.equal(r.status, 0, r.stderr);
    const report = await readFile(path.join(dir, 'docs', 'coherence-review.md'), 'utf8');
    assert.match(report, /## LLM enrichment/);
    assert.match(report, /under-rates the lite Documentalist/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('@integration document-review: --with-claude failure → honest fallback, no fabrication', async () => {
  const dir = await makeRepo();
  const fake = path.join(dir, 'fake-claude-fail.sh');
  await writeFile(fake, '#!/bin/sh\nexit 3\n');
  await chmod(fake, 0o755);
  try {
    const r = runMmd(dir, ['--with-claude'], { MMD_DOCUMENT_REVIEW_CMD: fake });
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /--with-claude enrichment unavailable/);
    const report = await readFile(path.join(dir, 'docs', 'coherence-review.md'), 'utf8');
    assert.match(report, /LLM enrichment unavailable/);
    assert.match(report, /No classification was fabricated/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('@integration document-review: missing claude binary → fallback (ENOENT), still exit 0', async () => {
  const dir = await makeRepo();
  try {
    const r = runMmd(dir, ['--with-claude'], { MMD_DOCUMENT_REVIEW_CMD: '/no/such/claude-binary-xyz' });
    assert.equal(r.status, 0, r.stderr);
    assert.match(r.stdout, /enrichment unavailable/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('@integration document-review: --help → exit 0 with usage; unknown flag → exit 2', async () => {
  const dir = await makeRepo();
  try {
    const help = runMmd(dir, ['--help']);
    assert.equal(help.status, 0);
    assert.match(help.stdout, /mmdream document-review/);
    assert.match(help.stdout, /--with-claude/);

    const bad = runMmd(dir, ['--bogus']);
    assert.equal(bad.status, 2);
    assert.match(bad.stderr, /unknown document-review arg/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});

test('@integration document-review: missing MAKE_MY_DREAMS.md → exit 4', async () => {
  const dir = await mkdtemp(path.join(tmpdir(), 'mmd-docreview-bare-'));
  try {
    await writeFile(path.join(dir, 'package.json'), '{"version":"0.7.0"}');
    const r = runMmd(dir, []);
    assert.equal(r.status, 4);
    assert.match(r.stderr, /cannot read MAKE_MY_DREAMS\.md/);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
});
